### PR TITLE
Converted to an AMD module with global fallback if there is no AMD Loader

### PR DESCRIPTION
**Pull request by mtscout6**
Here is the first option the Ben had mentioned in the [google groups post](http://groups.google.com/group/knockoutjs/browse_frm/thread/da84806ece82e5b0). Usage by those who wish to use the plugin with and AMD loader would need to do the following:

``` javascript
define(['order!util/knockout-2.1.0-pre', 'order!lib/knockout.mapping-2.0.3'], function (ko, mapping) {
    console.log('INFO - Registering Knockout Mapping 2.0.3 with Knockout 2.1.0-pre, registering any other mapping plug-in with Knockout 2.1.0-pre could be problematic.');
    mapping(ko);
});
```

Resubmitted For Original Pull Request #51

### CODE REVIEW

**Comment by neonstalwart** [comment]
if the order plugin is needed then something's not right.  

also, there are issues with the mapping plugin's version of `ko.exportSymbol` - see http://jsbin.com/ogirig/2/edit#javascript,html,live  a naive question... does the mapping plugin really need to define its own `ko.exportSymbol`?

**Comment by neonstalwart** [comment]
fyi - look at console for errors at http://jsbin.com/ogirig/2/edit#javascript,html,live

**Comment by domenic** [comment]
Why not make `knockout.mapping` depend on `knockout`? That would avoid this awkward exporting-of-factory-function thing.

**Comment by neonstalwart** [comment]
@domenic you're right but then you have to hard-code the id for `knockout` into `knockout.mapping` - what if i use `ko` and you use `knockout`?  which one should `knockout.mapping` have listed as a dependency?

this is a question that is being addressed on amd-implement (https://groups.google.com/forum/#!topic/amd-implement/_vt4K62no4M) and there is an answer (see "map" at https://gist.github.com/1630091) but its so new nobody has implemented it - except for dojo where the idea came from but it is currently implemented as `packageMap`.

in my opinion, your suggestion would be the best way to do it when the `map` option is implemented.  in my original discussion with @mtscout6 this was something i mentioned.

**Comment by neonstalwart** [comment]
@domenic maybe your approach would be best.  even though there are limitations to it (everyone has to use the same id, you can't load 2 versions of ko via amd that both use the mapping plugin) those limitations go away once `map` is implemented.  this might be better than writing an admittedly awkward function export that relies on the user to initialize the module.  hopefully the limitations will only be short term and it would mean that the code in `knockout.mapping` is done "right" the first time by anticipating the availability of `map` soon.

these are the kind of decisions where i can't really make a value judgment since i don't use `knockout.mapping` at all or even `ko` very much at all.  i've admitted from the start that the function export feels awkward.

**Comment by sagacity** [comment]
@neonstalwart I think the mapping plugin's version of ko.exportSymbol can be removed.

About the module, what about just reusing the module code from knockout? It's visible at the top here: https://github.com/SteveSanderson/knockout/blob/master/build/output/knockout-latest.debug.js

If not, can the pull request be adapted with @domenic's suggested changes?

**Comment by neonstalwart** [comment]
@RoyJacobs you can't use the exact same code as in knockout because you have a dependency on `ko`.  this is what our discussion is about - what's the best way to satisfy that dependency?  in amd, `ko` is not necessarily going to be a global so you have to get a reference to it as an amd dependency.  without all the boilerplate, it's basically this form:

``` js
define(['ko'], function (ko) {
     // define the mapping plugin in here using `ko` that's in scope
});
```

the problem is that we have declared a dependency on exactly `'ko'`.  someone might have a setup that has the knockout library as the `'knockout'` module id OR they might be running 2 versions of knockout as `'ko-2-0'` and `'ko-2-1'` (poor example but the use case is still valid).  in these cases where knockout is not identified by the `'ko'` module id, code needs to be changed somehow so that the mapping plugin will work.

however, even with all these downsides, maybe the hard coded dependency on `'ko'` is not too bad given that loaders are likely to support  the "map" option (outlined [here](https://gist.github.com/1630091)) in the not too distant future.  this still leaves the multiple version case unsolvable for now but i doubt anybody is currently using it since amd support for knockout was added so recently.

if you went this route, the boilerplate would be something like this:

``` js
(function (definition) {
    if (typeof define !== 'undefined' && define.amd) {
        define(['ko'], definition);
    }
    else {
        definition(window['ko']);
    }
}(function (ko) {

    // mapping plugin

}));
```

...and for anyone to use the mapping plugin right now, they need to put knockout at the `'ko'` module id.

**Comment by sagacity** [comment]
Ah right, so what's the solution everyone would be satisfied with for now and long-term? The one in the pull request, or do you need to make any changes?

**Comment by domenic** [comment]
Having looked into this more, here is my opinion---but I'd like input from others upthread.

`knockout.mapping` should take a hard-coded dependency on `"knockout"` (not `"ko"`, since we use long forms for other libraries: `"jquery"` instead of `"$"` and `"underscore"` instead of `"_"`).

People can use the abovementioned in-progress-of-being-standardized `map` to make sure `knockout.mapping` figures out what `knockout` refers to. For places where `map` isn't present, the worst thing that happens is people are forced to use `"knockout"` as Knockout's module ID.

---

**Furthermore**, if used as an AMD module, it should NOT create the `mapping` property on the `knockout` object. This kind of pseudo-namespacing via object literals is exactly the problem AMD is trying to solve. Instead, it should export all of its functions directly, so it could be used as so:

``` javascript
define(function (require) {
    var ko = require("knockout");
    var koMapping = require("knockout.mapping");

    ko.applyBindings({});
    koMapping.fromJS({});
});
```

If we like this idea, it's relatively easy to implement, and I can create a pull request if we want.

**Comment by neonstalwart** [comment]
I'm generally ok with that proposition. I'd use ko rather than knockout but that's not a deal breaker. 

I had the same thought to have mapping not augment ko but rather return its api and I was going to look into just how much the code actually depended on ko and see if it would be feasible to refactor the code to completely avoid the dependency on ko. I'm not at all familiar with the code in the mapping plugin and won't have time to look until Monday or later so I don't know if this is even remotely possible but removing the dependency on ko would be a good thing if it could be done in a way that makes sense.

Anyhow... +1 to @domenic

**Comment by sagacity** [comment]
@domenic, I quite like the fact that the mapping would become separated like that.

@neonstalwart, removing the dependency is impossible since the whole purpose of the plugin is to create Knockout observables, observable arrays, etc. Also, I don't think it needs to be separate, since it is specifically advertised as a _plugin_ to Knockout, not a separate lib. Do you see any benefit of it being completely separate, apart from the cleaner module structure?

**Comment by neonstalwart** [comment]
@RoyJacobs thanks - i obviously spoke without doing any thinking about that one :)

i use [dependency injection](https://github.com/cello/twine) and you start to see every little dependency as an opportunity for injection.  sometimes you can go too far.

**Comment by sagacity** [comment]
@neonstalwart That looks like a great project btw, please document it :)

**Comment by sagacity** [comment]
@domenic @neonstalwart Is either of you going ahead with the changes mentioned in this issue?

**Comment by mtscout6** [comment]
I have been using these changes for a week now, everything seems to be working great! It is working just fine with both version 2.1.0-pre and 1.2.1 of knockout. I am running both versions simultaneously!!

**Comment by sagacity** [comment]
@mtscout6 That is good news and you earn hacker points for running them side-by-side :) I was just wondering if the points raised in this issue will be addressed, or if we should just go ahead and use your module definition as-is.

**Comment by neonstalwart** [comment]
i'm not planning on working on anything - i was under the impression @domenic might be going to do something.

**Comment by domenic** [comment]
Sorry, slipped my mind! PR coming shortly :)

**Comment by sagacity** [comment]
Excellent :)

**Comment by domenic** [comment]
And here we are: https://github.com/SteveSanderson/knockout.mapping/pull/56

**Pull request closed without merging**
