### PR TITLE
fromJS fails with observableArray

### PR DESCRIPTION
**Pull request by joefeser**
I added two tests to demonstrate the failure.

Tested in FF 6 and Chrome.

Please contact me if you need more info.

### CODE REVIEW

**Comment by joefeser** [comment]
I was not calling items() but on the final test, the array update included two items and the length is still 3.

**Comment by sagacity** [comment]
Hi Joe,

I'm not completely sure what this patch fixes.

When I look at your tests, you write:
equal(viewModel.items.length, 1);

This fails (as you point out). However, since viewModel.items is an observableArray, the line should read:
equal(viewModel.items().length, 1);

This works even without your patch applied.

**Comment by joefeser** [comment]
Did you pull abb614a?
I fixed the other two issues. I did fix the () issue.
Look at line 1217.

ko.mapping.fromJS(newData, viewModel);
should have replaced the 3 element array with 2 correct?
equal(viewModel.items().length, 2); //should this be 2??

**Comment by sagacity** [comment]
I'm sorry, I did not! I didn't realize there were two commits. I'll get back to you on this.

**Comment by joefeser** [comment]
I was a moron with the first checkin. I realized after the fact that I needed the () on items.

The diff for abb614a does show my ID10T issue.

Sorry about the initial bad checkin.

**Comment by sagacity** [comment]
No apology necessary, I was just in a hurry and overlooked your other commit. I still didn't have time to properly look at your request though, but it will certainly be looked at sometime this week.

**Comment by sagacity** [comment]
@joefeser: Your unit test is failing because you did not create the original viewModel using 'ko.mapping.fromJS'. When doing the update, the mapping plugin assumes the second parameter you pass is either an object containing mapping options, or a previously mapped object.

In your case it is therefore using your viewModel as an options object. You can fix this by changing your 'ko.mapping.fromJS' to read:

``` javascript
ko.mapping.fromJS(newData, {}, viewModel);
```

**Comment by joefeser** [comment]
I am just following the example here http://knockoutjs.com/documentation/plugins-mapping.html.

Are you saying the array now updates correctly if it is the third item as shown in your above example?

**Comment by sagacity** [comment]
Yes, it would.

**Comment by sagacity** [comment]
Can this issue and pull request be closed?

**Comment by joefeser** [comment]
I will check today sorry.

Joe

**Comment by joefeser** [comment]
Bug in my code. issue never existed.

**Pull request closed without merging**
