### PR TITLE
programmatically omit a created item from the mapped array 

### PR DESCRIPTION
**Pull request by bytesandwich**
This commit gives the create function the option to omit its result from the mapped array if the parent is an array,
this is my solution for issue #82

### CODE REVIEW

**Comment by sagacity** [comment]
Hi Jack, there have been a few changes to the code that don't allow this pull request to be merged. Can you take the latest version and apply your changes there? Apart from that, though, would it not make more sense to allow the `ignore` option to be a callback function? Right now it's an array of property names (e.g.: `["ignoreMe"]`) but if I'm correct in parsing your requirements, you basically want an ignore callback instead of a static ignore array.

Perhaps this could then be extended further so that the other options (`include` and `copy`) also can supply callbacks.

**Comment by bytesandwich** [comment]
I'm not really seeing what you mean by callback. Options can't be a callback because then I lose access to the parent object and data, and if a callback is given in the options object, how can you differentiate the value passed to the callback in order to omit it from the resulting array. I mean what if I want undefined in the array?

 The problem I have is that even if I return undefined something gets pushed to the array if you are mapping a child of an array. I don't think there is much room for alternatives because the scope constructing the array has no access to the scope mapping the child (updateViewModel calls itself and doesn't have any handles to receive anything besides the return value), so I just put an identifier object in global scope so one can return it and the other can check against it.

**Comment by sagacity** [comment]
Sure, I see your point regarding the `undefined` (though I'm not sure how many times anyone'd want to ACTUALLY return that).

Before I merge, can you also add a unit test for updating existing arrays (e.g. first item is retained, second item is skipped and the third item gets added)?

And one final nitpick (sorry :)): Would it be okay if we rename `passOver` to `skip`? That seems slightly more descriptive to me, but that's just a personal preference.

**Comment by bytesandwich** [comment]
Sorry for the delay. 
I added the test and rebased (I can't see anything wrong, but I don't rebase frequently), as well as changed the property to skip.

**Comment by sagacity** [comment]
Thanks! This is now merged.

**Pull request merged**
