### PR TITLE
adding mappedPush that uses create callback and key callback

### PR DESCRIPTION
**Pull request by vantreeseba**
adding mappedPush that uses create callback and key callback to ensure uniqueness and to allow easier and cleaner access to child mapped view models

Created tests for this, and they are passing.  Let me know if theres anything else you think I should do for this before trying to push again.

### CODE REVIEW

**Comment by sagacity** [comment]
Thanks for this! I'm just wondering if a name other than 'mappedPush' might be more suitable, since it doesn't actually follow array.push semantics. It's more like setting a key in a dictionary to a certain value.

Do you have any suggestions for alternate names?

**Comment by vantreeseba** [comment]
mappedCreate or mappedInsert are the other names I was thinking, since both really create more connotations with creating/adding an existing item to the array.  I suppose it wouldn't really be difficult to modify it to follow the array.push semantics further (I am assuming you mean taking in an array of arguments compared to a single?)

And don't thank me, this plugin + knockout save me so much work its silly :P

**Comment by sagacity** [comment]
I'm sorry, I wasn't clear: the semantics of array.push are that it _always_ adds a new element to the end of the array, regardless if it's a duplicate or not. In this case, you have set/dictionary semantics, since you don't allow duplicates.

`mappedCreate` makes the most sense I think, since it is precisely what you are doing. I would prefer that `mappedCreate` also returns the item it has created. If the item already exists in the array, it should probably throw an exception (although maybe you can explain a bit more what your intended use case is).

Alternatively, it can return the existing object if it was already in the array, but then it should not be called `mappedCreate`, since it doesn't always create an item.

Sorry for the complications :)

**Comment by vantreeseba** [comment]
Oh no you're fine, thanks for clearing that up though, I'll look at patching it a bit later to make these changes.
I'm not sure if an exception on duplicates or returning the duplicate would be more "expected" behavior, but thats something easy to change as well.

**Pull request merged**
