### PR TITLE
Now usable as a CommonJS, Node, or AMD module.

### PR DESCRIPTION
**Pull request by domenic**
- Behavior when used as a `<script>` tag unchanged: still adds a `mapping` property to the global `ko` object.
- Declares itself as an anonymous module.
- Takes a hard-coded dependency on the module ID "knockout". Use mapping features of your module system if necessary.
- Closure Compiler helper stuff removed.

As discussed in GH-51, GH-52, and <a href="https://groups.google.com/forum/?fromgroups#!topic/knockoutjs/2oSAbs6C5bA">Google Groups</a>.

### CODE REVIEW

**Comment by neonstalwart** [comment]
nice

**Comment by sagacity** [comment]
Excellent, thanks a lot! I'll do the merge sometime tomorrow.

**Comment by sagacity** [comment]
This has now been merged: f996b65ce93ccb934746fdb581dc2060359f9326

**Comment by mak0t0san** [comment]
When used as a module, it doesn't seem to be adding the mapping property to ko.  I'm assuming we're supposed to treat it as a separate module rather than a plugin?

ie:
define(['knockout','knockout.mapping'......],function(ko, mapping){
  // Code goes here
});

**Comment by neonstalwart** [comment]
@mak0t0san yes you should treat it as a separate module.

**Pull request closed without merging**
