### PR TITLE
Add support for mapping arrays of primitive objects.

### PR DESCRIPTION
**Pull request by mackd**
When mapping an object with something like this:

``` javascript
{
    /* other properties... */

    test: ["string 1", "string 2"]
}
```

My intuitive expectation is that this will be mapped to an array of observables, but this is not happening.

I hacked a local copy to get it working how I expected.  See this pull request for my code.

### CODE REVIEW

**Comment by jamesfoster** [comment]
you can use the mapping options to do this

``` javascript
var data = {
  test: [1,2,3,4]
  // ...
}

var mapping = {
  test: {
    create: function(options){
      return new ko.observable(options.data);
    }
  }
}

var viewModel = ko.mapping.fromJS(data, mapping);
```

this will wrap the elements of the array `test` in observables.

**Comment by mackd** [comment]
Updated to add configuration and tests.

**Comment by sagacity** [comment]
Hi David, apologies for the slow reply. Regarding your changes, jamesfoster's response shows how to do this without changing the plugin. Additionally, because this new behavior is not "opt-in" as far as I can tell, existing users of the plugin would be affected. So, I'm sorry, but this is why I am hesitant to merge these changes.

Edit: It _is_ opt-in, that is a good thing :) But again, what you are trying to do is already possible with the existing plugin.

**Comment by mackd** [comment]
jamesfoster's suggestion is a good one and I tried it before hacking the plugin, but it doesn't work.  Here's a test that shows the failure:

``` javascript
test('ko.mapping.fromJS should return an observableArray if you supply an array, and should wrap its entries in observables if there is a create mapping that does this', function () {
        var sampleArray = {array: ["a", "b"]};
        var result = ko.mapping.fromJS(sampleArray, {
                array: {
                        create: function(options) {
                                return new ko.observable(options.data);
                        }
                }
        });
        equal(result.array().length, 2);
        equal(ko.isObservable(result.array()[0]),true);
        equal(ko.isObservable(result.array()[1]),true);
        equal(result.array()[0](), "a");
        equal(result.array()[1](), "b");
});
```

It seems like the mapping for arrays iterates through each array element, calling updateViewModel (which wraps the array element in an observable even without the create mapping), but then immediately unwraps the entry in all cases, effectively undoing the custom mapping.  Perhaps someone smarter than me can figure out how to work around this without implementing my configuration option.

Edit: And I don't mean that sarcastically, I think using a 'create' mapping would be the optimal way to accomplish this.

**Comment by jamesfoster** [comment]
He's right. Apologies for not double checking. Every element of a mapped array is never observable because of this line:

https://github.com/SteveSanderson/knockout.mapping/blob/bd9669e91/knockout.mapping.js#L486

I think that **whatever** `create` returns should be the value stored in the array. No question. I'd say this is a bug and not expected behaviour. The default behaviour (without a `create` method) can remain the same, i.e. unwrapping the elements.

So, instead of (or as well as?) the `observableArrayEntities` option, look to see if there's a `create` method.

@mackd's test above should probably be added to the suite.

**Comment by sagacity** [comment]
Yes, I agree that it's a bug. The proposed fix of just checking for the `create` method would be sufficient, I suppose.
Thanks for helping out, guys :)

If anyone's interested in creating a new pull request with this fix and the appropriate tests it would be much appreciated, otherwise I'll have to do it when there's some more spare time.

**Comment by mackd** [comment]
This was superseded by #50, which fixes the underlying bug rather than introducing a new configuration option.

**Pull request closed without merging**
