### PR TITLE
Converted to an AMD module with global fallback if there is no AMD Loader

### PR DESCRIPTION
**Pull request by mtscout6**
Here is the first option the Ben had mentioned in the [google groups post](http://groups.google.com/group/knockoutjs/browse_frm/thread/da84806ece82e5b0). Usage by those who wish to use the plugin with and AMD loader would need to do the following:

``` javascript
define(['order!util/knockout-2.1.0-pre', 'order!lib/knockout.mapping-2.0.3'], function (ko, mapping) {
    console.log('INFO - Registering Knockout Mapping 2.0.3 with Knockout 2.1.0-pre, registering any other mapping plug-in with Knockout 2.1.0-pre could be problematic.');
    mapping(ko);
});
```

### CODE REVIEW

**Comment by sagacity** [comment]
Excellent! A small thing: Can you change your pull request to only contain the root "knockout.mapping.js" file? If I only checkout that file from your repo, the history is lost, and I want to maintain it.

**Comment by neonstalwart** [comment]
fyi - make sure that you're both comfortable that this is the best approach - its kind of awkward to return a factory that needs `ko` passed to it.  however, i feel that its probably the best out of a few "less than ideal" options but maybe some time to think about it will produce a better option.

if you're both satisfied that this is the most suitable option then the implementation looks good to me.

**Comment by neonstalwart** [comment]
btw, @mtscout6 you shouldn't need to use the order plugin to load this.  that's the point of returning a function - you control the initialization order by when you call the function.  the comments in your code show how i think it should be used but the example in your first comment above shouldn't need the order plugin.  did you find that it was necessary?

**Comment by mtscout6** [comment]
Ben - I did find that it was necessary, I'm still not sure why though. I'm guessing right now that it is due to my dual usage of two version of knockout simultaneously on the page. I still need to follow through with that investigation.

Roy - I will resubmit the request with only that file changed, I'm leaving in the .gitignore change I added for a vim generated file though.

**Pull request closed without merging**
