### PR TITLE
Feature addition (Issue #114)

### PR DESCRIPTION
**Pull request by supergibbs**
See [readme.md](https://github.com/supergibbs/knockout.mapping) for details, but adds a new observe array option. Tests are included as well.

### CODE REVIEW

**Comment by sagacity** [comment]
Nice work, thanks! I'll try to merge it in asap.

**Comment by supergibbs** [comment]
Cool, I'll start moving the documentation ~~(you can ignore the README.md)~~ You can delete my additions to the README.md since I've added it to the gh-pages knockout branch

**Comment by sagacity** [comment]
Ok, to confirm: The merge would then be for commits a515e38 and 7569eac?

**Comment by supergibbs** [comment]
I am new to pull requests on github but isn't it just like a remote pull in git? If so, the last commit is all you need. 

Would it be easier if I committed once more to revert the README.md to your copy? 

Either that or pull in the latest commit then edit the README.md yourself and delete my additions. I've moved them to a new pull request for the gh-pages anyway. 

I think my comment above was confusing... I fixed it :-)

**Comment by sagacity** [comment]
Yes that was a bit unclear :)

But if the last commit is the only one that's needed, that's fine. For reference, to "clean up" your pull request, you would need to create a new branch in your fork, only merge in the appropriate commit (7569eac I guess) and do a new pull request of that branch. This will then only contain THAT commit, and not the other ones.

**Comment by supergibbs** [comment]
My clean up was just on knockout.mapping.js to get rid of whitespace changes. I've now committed a clean version (fbde1af) that reverts the README.md. 

Just merge the latest commit and it will only add the new feature and tests. Hope that works!

Update: Sorry I see what's going on here... Want me to make a new clean branch or do you have the option of pulling the whole master branch and squashing the commits? Let me know whats easiest for you. 

My second github contribution will go much smoother I hope :)

**Comment by sagacity** [comment]
Yes, I can certainly do a manual merge, so don't worry. :)

**Comment by sagacity** [comment]
No hang on, it's actually a bit messier than that. Could you maybe do the clean branch and only apply relevant changes there?

**Comment by supergibbs** [comment]
Canceled and new clean branch request (Issue # 117)

**Pull request closed without merging**
