### PR TITLE
Fix/unify options merging

### PR DESCRIPTION
**Pull request by DzenisevichK**
Fix for #39, #61, #62 issues

### CODE REVIEW

**Comment by sagacity** [comment]
Excellent work. Let me review the patch and I'll try to merge it asap.

**Comment by DzenisevichK** [comment]
Good!
There are also pending improvements but only after merging current request...

**Comment by sagacity** [comment]
Will you also be fixing the failing test (thanks for that too!) or should I handle it? Either is fine, I just want to know what your intentions are.

**Comment by DzenisevichK** [comment]
Yes, will fix in one hour.

**Comment by DzenisevichK** [comment]
Do we need export visitModel?
visitModel has the same abstraction level as updateViewModel and visitPropertiesOrArrayEntries...

The same also for getType that not related to ko.mapping stuff at all.

**Comment by sagacity** [comment]
I don't think anyone will miss `visitModel`, since it's undocumented.

I do want to export `getType` though, because I want to allow other types to be treated properly as wel. For instance, I'm using the `XDate` library in my codebase at work, and I want to be able to have `getType` return "date" for all `XDate` instances as well. So I need to be able to extend it. If you have an alternative solution to handle this that would be certainly be okay too.

**Comment by DzenisevichK** [comment]
It's enough for the request and I'm waiting for merging...

**Comment by sagacity** [comment]
Hmm, I'm seeing some issues. Occasionally the mapping options object itself (e.g. everything in `__ko_mapping__`) gets mapped as well! I haven't been able to reproduce this yet.

@DzenisevichK do you know what could be causing this behavior? It has to do with converting to JSON and then using that as a source to map again, I think.

**Comment by DzenisevichK** [comment]
May you create a unit test on jsfiddle to reproduce this?

**Comment by sagacity** [comment]
Yes, I'll try to do that.

**Comment by sagacity** [comment]
I have added a failing test. Basically, when using the `create` callback I would still expect that explicitly provided options like `include` get used. Instead they get overwritten at the start of `visitModel`.

Maybe it's not as clean when an `include` on the highest level is also used on child/nested objects though, so a different approach is also welcome.

**Comment by DzenisevichK** [comment]
Yes, this is not logically to use options for root object in nested!

Problem not in the pull request but in the options' notation at all. We need to create a new issue for discussion options' notation.

**Comment by sagacity** [comment]
@DzenisevichK Can you also take a look at issue #67?

**Comment by DzenisevichK** [comment]
Roy, please look on [changes](https://github.com/DzenisevichK/knockout.mapping/commits/) in my fork...
I'm also planning to implement [js-traverse's](https://github.com/substack/js-traverse) way of transforming objects in ko.mapping library.

**Comment by sagacity** [comment]
Excellent work! It'll take some time for me to review everything, but it seems very nice.
Just curious, what would be the benefit of the js-traverse approach? (I'm not saying it is bad, just curious)

**Comment by DzenisevichK** [comment]
1) js-traverse approach is very flexible - not limited to any format of options - you may specify callback and based on mapping state as context of callback do any additional to wrap/unwrap transforming.
2) toJS and fromJS will be symmetric.
3) Don't save mapping state in object (reduce memory + also don't limit objects range).
...

**Comment by sagacity** [comment]
Sounds very interesting. I'm very pleased with the way you are reducing the code complexity, by the way!

**Pull request merged**
